// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ThailandpostTracking.Models;

namespace ThailandpostTracking.Data
{
    public partial class AppDBContext : DbContext
    {
        public AppDBContext()
        {
        }

        public AppDBContext(DbContextOptions<AppDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TmpImportTracking> TmpImportTrackings { get; set; }
        public virtual DbSet<TrackingBatch> TrackingBatches { get; set; }
        public virtual DbSet<TrackingDetail> TrackingDetails { get; set; }
        public virtual DbSet<TrackingHeader> TrackingHeaders { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Thai_100_CI_AI");

            modelBuilder.Entity<TmpImportTracking>(entity =>
            {
                entity.Property(e => e.TmpImportTrackingId).ValueGeneratedNever();
            });

            modelBuilder.Entity<TrackingBatch>(entity =>
            {
                entity.Property(e => e.TrackingBatchId).ValueGeneratedNever();

                entity.Property(e => e.TrackingBatchTypeId).HasComment("1 Insert,2 Upsert ");
            });

            modelBuilder.Entity<TrackingDetail>(entity =>
            {
                entity.Property(e => e.TrackingDetailId).ValueGeneratedNever();

                entity.Property(e => e.Call_Center_Tel).HasComment("THP Contact Center");

                entity.Property(e => e.Delivery_Datetime).HasComment("วันที่จัดส่ง");

                entity.Property(e => e.Delivery_Description).HasComment("คำอธิบายการจัดส่ง");

                entity.Property(e => e.Delivery_Officer_Name).HasComment("ชื่อเจ้าหน้าที่นำจ่าย");

                entity.Property(e => e.Delivery_Officer_Tel).HasComment("เบอร์ติดต่อเจ้าหน้าที่นำจ่าย");

                entity.Property(e => e.Delivery_Status).HasComment("สถานะการจัดส่ง");

                entity.Property(e => e.Location).HasComment("สถานที่ตั้ง");

                entity.Property(e => e.Office_Name).HasComment("ชื่อที่ทำการไปรษณีย์");

                entity.Property(e => e.Office_Tel).HasComment("เบอร์ติดต่อที่ทำการไปรษณีย์");

                entity.Property(e => e.Postcode).HasComment("รหัสไปรษณีย์");

                entity.Property(e => e.Receiver_Name).HasComment("ชื่อผู้รับ");

                entity.Property(e => e.Signature).HasComment("ลายเซ็น");

                entity.Property(e => e.Status).HasComment("สถานะ");

                entity.Property(e => e.StatusDetail).HasComment("รายละเอียดเพิ่มเติมของสถานะ");

                entity.Property(e => e.Status_Date).HasComment("สถานะของวันที่");

                entity.Property(e => e.Status_Description).HasComment("คำอธิบายสถานะ");

                entity.HasOne(d => d.TrackingBatch)
                    .WithMany(p => p.TrackingDetails)
                    .HasForeignKey(d => d.TrackingBatchId)
                    .HasConstraintName("FK_TrackingDetail_TrackingBatch");

                entity.HasOne(d => d.TrackingHeader)
                    .WithMany(p => p.TrackingDetails)
                    .HasForeignKey(d => d.TrackingHeaderId)
                    .HasConstraintName("FK_TrackingDetail_TrackingHeader");
            });

            modelBuilder.Entity<TrackingHeader>(entity =>
            {
                entity.Property(e => e.TrackingHeaderId).ValueGeneratedNever();

                entity.Property(e => e.Call_Center_Tel).HasComment("THP Contact Center");

                entity.Property(e => e.Delivery_Datetime).HasComment("วันที่จัดส่ง");

                entity.Property(e => e.Delivery_Description).HasComment("คำอธิบายการจัดส่ง");

                entity.Property(e => e.Delivery_Officer_Name).HasComment("ชื่อเจ้าหน้าที่นำจ่าย");

                entity.Property(e => e.Delivery_Officer_Tel).HasComment("เบอร์ติดต่อเจ้าหน้าที่นำจ่าย");

                entity.Property(e => e.Delivery_Status).HasComment("สถานะการจัดส่ง");

                entity.Property(e => e.Location).HasComment("สถานที่ตั้ง");

                entity.Property(e => e.Office_Name).HasComment("ชื่อที่ทำการไปรษณีย์");

                entity.Property(e => e.Office_Tel).HasComment("บอร์ติดต่อที่ทำการไปรษณีย์");

                entity.Property(e => e.Postcode).HasComment("รหัสไปรษณีย์");

                entity.Property(e => e.Receiver_Name).HasComment("ชื่อผู้รับ");

                entity.Property(e => e.Signature).HasComment("ลายเซ็น");

                entity.Property(e => e.Status).HasComment("สถานะ");

                entity.Property(e => e.StatusDetail).HasComment("รายละเอียดเพิ่มเติมของสถานะ");

                entity.Property(e => e.Status_Date).HasComment("สถานะของวันที่");

                entity.Property(e => e.Status_Description).HasComment("คำอธิบายสถานะ");

                entity.HasOne(d => d.TrackingBatch)
                    .WithMany(p => p.TrackingHeaders)
                    .HasForeignKey(d => d.TrackingBatchId)
                    .HasConstraintName("FK_TrackingHeader_TrackingBatch");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}