// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using ThailandpostTracking.Models;

namespace ThailandpostTracking.Data
{
    public partial interface IAppDBContextProcedures
    {
        Task<List<usp_ReportTracking_SelectResult>> usp_ReportTracking_SelectAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
