// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ThailandpostTracking.Models
{
    [Table("TrackingDetail")]
    public partial class TrackingDetail
    {
        [Key]
        public Guid TrackingDetailId { get; set; }
        public Guid? TrackingHeaderId { get; set; }
        public Guid? TrackingBatchId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Status { get; set; }
        [StringLength(255)]
        public string Status_Description { get; set; }
        public DateTime? Status_Date { get; set; }
        public string StatusDetail { get; set; }
        [StringLength(255)]
        public string Location { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Postcode { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Delivery_Status { get; set; }
        [StringLength(255)]
        public string Delivery_Description { get; set; }
        public DateTime? Delivery_Datetime { get; set; }
        [StringLength(255)]
        public string Receiver_Name { get; set; }
        public string Signature { get; set; }
        [StringLength(255)]
        public string Delivery_Officer_Name { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Delivery_Officer_Tel { get; set; }
        [StringLength(255)]
        public string Office_Name { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Office_Tel { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Call_Center_Tel { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [ForeignKey("TrackingBatchId")]
        [InverseProperty("TrackingDetails")]
        public virtual TrackingBatch TrackingBatch { get; set; }
        [ForeignKey("TrackingHeaderId")]
        [InverseProperty("TrackingDetails")]
        public virtual TrackingHeader TrackingHeader { get; set; }
    }
}