// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ThailandpostTracking.Models
{
    [Table("TrackingBatch")]
    public partial class TrackingBatch
    {
        public TrackingBatch()
        {
            TrackingDetails = new HashSet<TrackingDetail>();
            TrackingHeaders = new HashSet<TrackingHeader>();
        }

        [Key]
        public Guid TrackingBatchId { get; set; }
        public string JsonResponse { get; set; }
        /// <summary>
        /// 1 Insert,2 Upsert 
        /// </summary>
        public int? TrackingBatchTypeId { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [InverseProperty("TrackingBatch")]
        public virtual ICollection<TrackingDetail> TrackingDetails { get; set; }
        [InverseProperty("TrackingBatch")]
        public virtual ICollection<TrackingHeader> TrackingHeaders { get; set; }
    }
}